
const productsData = [
    {
        key: '1',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'inactive',
        img: 'sarees.jpg'
    },
    {
        key: '2',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'inactive',
        img: 'handbags.jpg',
    },
    {
        key: '3',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'inactive',
        img: 'salwarsuit.jpg',
    },
    {
        key: '4',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'accessories.jpg',
    },

    {
        key: '5',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'hometheatre.jpg',
    },
    {
        key: '6',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'avileatherwallet.jpg',
    },
    {
        key: '7',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'car.jpg',
    },
    {
        key: '8',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'fashion.jpg',
    },
    {
        key: '9',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'jacket.jpg',
    },
    {
        key: '10',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'menwallet.jpg',
    },
    {
        key: '11',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'mitv.jpg',
    },
    {
        key: '12',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'nikeshoes.jpg',
    },
    {
        key: '13',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'onidatv.jpg',
    },
    {
        key: '14',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'powerbank.jpg',
    },
    {
        key: '15',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'shirt.jpg',
    },
    {
        key: '16',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'smartphone.jpg',
    },
    {
        key: '17',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'sunglasses.jpg',
    },
    {
        key: '18',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'watches.jpg',
    },
    {
        key: '19',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'camera.jpg',
    },
    {
        key: '20',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'shoes.jpg',
    },

    {
        key: '21',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        img: 'oven.jpg',
    },
    {
        key: '22',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        img: 'tv.jpg',
    },
    {
        key: '23',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        img: 'samsungphone.jpg',
    },

    {
        key: '24',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        img: 'sarees.jpg',
    },
    {
        key: '25',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        img: 'handbags.jpg',
    },
    {
        key: '26',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        img: 'salwarsuit.jpg',
    },
    {
        key: '27',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'accessories.jpg',
    },

    {
        key: '28',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'hometheatre.jpg',
    },
    {
        key: '29',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 150,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'avileatherwallet.jpg',
    },
    {
        key: '30',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 190,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'car.jpg',
    },
    {
        key: '31',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'fashion.jpg',
    },
    {
        key: '32',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'jacket.jpg',
    },
    {
        key: '33',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'menwallet.jpg',
    },
    {
        key: '34',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'mitv.jpg',
    },
    {
        key: '35',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'nikeshoes.jpg',
    },
    {
        key: '36',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'onidatv.jpg',
    },
    {
        key: '37',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        img: 'powerbank.jpg',
    },
    {
        key: '38',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '39',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },
    {
        key: '40',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: sunglasses,
    },
    {
        key: '41',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: watches,
    },
    {
        key: '42',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: camera,
    },
    {
        key: '43',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shoes,
    },

    {
        key: '44',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: oven,
    },
    {
        key: '45',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: tv,
    },
    {
        key: '46',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: samsungphone,
    },

    {
        key: '47',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: sarees,
    },
    {
        key: '48',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        // link: 'https://www.amazon.in',
        status: 'active',
        // img: handbags,
    },
    {
        key: '49',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: salwarsuit,
    },
    {
        key: '50',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: accessories,
    },

    {
        key: '51',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: hometheatre,
    },
    {
        key: '52',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: avileatherwallet,
    },
    {
        key: '53',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: car,
    },
    {
        key: '54',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: fashion,
    },
    {
        key: '55',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: jacket,
    },
    {
        key: '56',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: menwallet,
    },
    {
        key: '57',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: mitv,
    },
    {
        key: '58',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: nikeshoes,
    },
    {
        key: '59',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: onidatv,
    },
    {
        key: '60',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: powerbank,
    },
    {
        key: '61',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '62',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },
    {
        key: '63',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: sunglasses,
    },
    {
        key: '64',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: watches,
    },
    {
        key: '65',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: camera,
    },
    {
        key: '66',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shoes,
    },

    {
        key: '67',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: oven,
    },
    {
        key: '68',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: tv,
    },
    {
        key: '69',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: samsungphone,
    },

    {
        key: '70',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: sarees,
    },
    {
        key: '71',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: handbags,
    },
    {
        key: '72',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: salwarsuit,
    },
    {
        key: '73',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: accessories,
    },

    {
        key: '74',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: hometheatre,
    },
    {
        key: '75',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: avileatherwallet,
    },
    {
        key: '76',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: car,
    },
    {
        key: '77',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: fashion,
    },
    {
        key: '78',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: jacket,
    },
    {
        key: '79',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: menwallet,
    },
    {
        key: '80',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: mitv,
    },
    {
        key: '81',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: nikeshoes,
    },
    {
        key: '82',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: onidatv,
    },
    {
        key: '83',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: powerbank,
    },
    {
        key: '84',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '85',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },
    {
        key: '86',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: sunglasses,
    },
    {
        key: '87',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: watches,
    },
    {
        key: '88',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: camera,
    },
    {
        key: '89',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shoes,
    },

    {
        key: '90',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: oven,
    },
    {
        key: '91',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: tv,
    },
    {
        key: '92',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: samsungphone,
    },

    {
        key: '93',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: sarees,
    },
    {
        key: '94',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: handbags,
    },
    {
        key: '95',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: salwarsuit,
    },
    {
        key: '96',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: accessories,
    },

    {
        key: '97',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: hometheatre,
    },
    {
        key: '98',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: avileatherwallet,
    },
    {
        key: '99',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: car,
    },
    {
        key: '100',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: fashion,
    },
    {
        key: '101',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: jacket,
    },
    {
        key: '102',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: menwallet,
    },
    {
        key: '103',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: mitv,
    },
    {
        key: '104',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: nikeshoes,
    },
    {
        key: '105',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: onidatv,
    },
    {
        key: '106',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: powerbank,
    },
    {
        key: '107',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '108',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },
    {
        key: '109',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: sunglasses,
    },
    {
        key: '110',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: watches,
    },
    {
        key: '111',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: camera,
    },
    {
        key: '112',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shoes,
    },

    {
        key: '113',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: oven,
    },
    {
        key: '114',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: tv,
    },
    {
        key: '115',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: samsungphone,
    },

    {
        key: '116',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: sarees,
    },
    {
        key: '117',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: handbags,
    },
    {
        key: '118',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: salwarsuit,
    },
    {
        key: '119',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: accessories,
    },

    {
        key: '120',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: hometheatre,
    },
    {
        key: '121',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: avileatherwallet,
    },
    {
        key: '122',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: car,
    },
    {
        key: '123',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: fashion,
    },
    {
        key: '124',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: jacket,
    },
    {
        key: '125',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: menwallet,
    },
    {
        key: '126',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: mitv,
    },
    {
        key: '127',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: nikeshoes,
    },
    {
        key: '128',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: onidatv,
    },
    {
        key: '129',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: powerbank,
    },
    {
        key: '130',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '131',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },
    {
        key: '132',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: sunglasses,
    },
    {
        key: '133',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: watches,
    },
    {
        key: '134',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: camera,
    },
    {
        key: '135',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shoes,
    },

    {
        key: '136',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: oven,
    },
    {
        key: '137',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: tv,
    },
    {
        key: '138',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: samsungphone,
    },

    {
        key: '139',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: sarees,
    },
    {
        key: '140',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: handbags,
    },
    {
        key: '141',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: salwarsuit,
    },
    {
        key: '142',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: accessories,
    },

    {
        key: '143',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: hometheatre,
    },
    {
        key: '144',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: avileatherwallet,
    },
    {
        key: '145',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: car,
    },
    {
        key: '146',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: fashion,
    },
    {
        key: '147',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: jacket,
    },
    {
        key: '148',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: menwallet,
    },
    {
        key: '149',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: mitv,
    },
    {
        key: '150',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: nikeshoes,
    },
    {
        key: '151',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: onidatv,
    },
    {
        key: '152',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: powerbank,
    },
    {
        key: '153',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '154',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },
    {
        key: '155',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: sunglasses,
    },
    {
        key: '156',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: watches,
    },
    {
        key: '157',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: camera,
    },
    {
        key: '158',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shoes,
    },

    {
        key: '159',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: oven,
    },
    {
        key: '160',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: tv,
    },
    {
        key: '161',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: samsungphone,
    },

    {
        key: '162',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: sarees,
    },
    {
        key: '163',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: handbags,
    },
    {
        key: '164',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: salwarsuit,
    },
    {
        key: '165',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: accessories,
    },

    {
        key: '166',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: hometheatre,
    },
    {
        key: '167',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: avileatherwallet,
    },
    {
        key: '168',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: car,
    },
    {
        key: '169',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: fashion,
    },
    {
        key: '170',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: jacket,
    },
    {
        key: '171',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: menwallet,
    },
    {
        key: '172',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: mitv,
    },
    {
        key: '173',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: nikeshoes,
    },
    {
        key: '174',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: onidatv,
    },
    {
        key: '175',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: powerbank,
    },
    {
        key: '176',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '177',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },
    {
        key: '178',
        batchId: '#826',
        family: 'Sunglasses',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: sunglasses,
    },
    {
        key: '179',
        batchId: '#819',
        family: 'Watches',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: watches,
    },
    {
        key: '180',
        batchId: '#473',
        family: 'Camera',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: camera,
    },
    {
        key: '181',
        batchId: '#426',
        family: 'Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shoes,
    },

    {
        key: '182',
        batchId: '#372',
        family: 'Oven',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: oven,
    },
    {
        key: '183',
        batchId: '#391',
        family: 'Television',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: tv,
    },
    {
        key: '184',
        batchId: '#556',
        family: 'Samsung Phone',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: samsungphone,
    },

    {
        key: '185',
        batchId: '#123',
        family: 'Sarees',
        source: 'Amazon',
        results: 85,
        imported: 85,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.google.com',
        status: 'active',
        // img: sarees,
    },
    {
        key: '186',
        batchId: '#456',
        family: 'Handbags',
        source: 'Amazon',
        results: 12,
        imported: 12,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.amazon.in',
        status: 'active',
        // img: handbags,
    },
    {
        key: '187',
        batchId: '#789',
        family: 'Salwar Suit',
        source: 'Flipkart',
        results: 9,
        imported: 9,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.flipkart.com',
        status: 'active',
        // img: salwarsuit,
    },
    {
        key: '188',
        batchId: '#849',
        family: 'Accessories',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: accessories,
    },

    {
        key: '189',
        batchId: '#921',
        family: 'Home Theatre',
        source: 'Flipkart',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: hometheatre,
    },
    {
        key: '190',
        batchId: '#164',
        family: 'Leather Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: avileatherwallet,
    },
    {
        key: '191',
        batchId: '#612',
        family: 'Car',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: car,
    },
    {
        key: '192',
        batchId: '#613',
        family: 'Fashion',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: fashion,
    },
    {
        key: '193',
        batchId: '#614',
        family: 'Jacket',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: jacket,
    },
    {
        key: '194',
        batchId: '#149',
        family: 'Men Wallet',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: menwallet,
    },
    {
        key: '195',
        batchId: '#235',
        family: 'MI TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: mitv,
    },
    {
        key: '196',
        batchId: '#012',
        family: 'Nike Shoes',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: nikeshoes,
    },
    {
        key: '197',
        batchId: '#172',
        family: 'Onida TV',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: onidatv,
    },
    {
        key: '198',
        batchId: '#139',
        family: 'Powerbank',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: powerbank,
    },
    {
        key: '199',
        batchId: '#110',
        family: 'Shirt',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: shirt,
    },
    {
        key: '200',
        batchId: '#582',
        family: 'Smartphone',
        source: 'Amazon',
        results: 300,
        imported: 300,
        lastUpdated: 'March 10, 2022',
        link: 'https://www.jiomart.com/',
        status: 'active',
        // img: smartphone,
    },

]

module.exports = productsData;